export const SECTIONS = {
  SELECTS: 'Tlon Selects',
  PALS: 'Powered by Pals',
  DEV: 'Develop on Urbit',
  USEFUL: 'Make Urbit Useful',
  FUN: 'Make Urbit Fun',
};

export const APPS = [
  {
    title: 'pals',
    description: 'friendlist for peer discovery',
    color: '#99D3BD',
    link: '/apps/pals',
    source: '~paldev',
    section: SECTIONS.SELECTS,
    desk: 'pals',
  },
  {
    title: 'Terminal',
    description: "A web interface to your Urbit's command line",
    color: '#233D34',
    link: '/apps/webterm',
    section: SECTIONS.SELECTS,
    desk: 'webterm',
    source: '~mister-dister-dozzod-dozzod',
  },
  {
    title: 'face',
    description: 'see your friends',
    color: '#3B5998',
    link: '/apps/face',
    source: '~paldev',
    section: SECTIONS.PALS,
    desk: 'face',
  },
  {
    title: 'rumors',
    description: 'Anonymous gossip from friends of friends',
    color: '#BB77DD',
    link: '/apps/rumors',
    source: '~paldev',
    section: SECTIONS.PALS,
    desk: 'rumors',
  },
  {
    title: 'Contacts',
    description: 'Contact book',
    color: '#338899',
    link: '/apps/whom',
    section: SECTIONS.PALS,
    source: '~holnes',
    desk: 'whom',
  },
  {
    title: "sc'o're",
    description: "leaderboard for groups' ['o']s, as seen on tv!",
    color: '#FFFF00',
    link: '/apps/scooore',
    source: '~paldev',
    section: SECTIONS.PALS,
    desk: 'scooore',
  },
  {
    title: 'Docs',
    description: 'User and developer documentation for Urbit apps',
    color: '#FFCF00',
    link: '/apps/docs',
    section: SECTIONS.DEV,
    desk: 'docs',
    source: '~pocwet',
  },
  {
    title: 'Quorum',
    description:
      'A choral explanations app (a la Stack Overflow or Quora) for Urbit',
    color: '#F2F2F2',
    link: '/apps/quorom',
    section: SECTIONS.DEV,
    desk: 'quorum',
    source: '~dister-dister-sidnum-ladrut',
    image: 'https://ladrut.xyz/quorum/quorum-logo.png',
  },
  {
    title: 'cliff',
    description: 'filesystem explorer',
    color: '#E39871',
    link: '/apps/cliff',
    section: SECTIONS.DEV,
    desk: 'cliff',
    source: '~paldev',
  },
  {
    title: 'silo',
    description: 'An S3 storage manager',
    color: '#4F46E5',
    link: '/apps/silo',
    section: SECTIONS.USEFUL,
    source: '~dister-nocsyx-lassul',
    desk: 'silo',
  },
  {
    title: 'Grove (alpha)',
    description: 'Groups file drive',
    color: '#e5e7eb',
    link: '/apps/grove',
    section: SECTIONS.USEFUL,
    source: '~dister-dozzod-dalten',
    desk: 'grove',
    image: 'https://freedom-club.sfo2.digitaloceanspaces.com/grove.png',
  },
  {
    title: 'hodl',
    description: 'A portfolio for all that you hodl',
    color: '#B8A3D1',
    link: '/apps/hodl',
    section: SECTIONS.USEFUL,
    desk: 'hodl',
    source: '~hodler-datder-sonnet',
    image:
      'https://user-images.githubusercontent.com/16504501/194947852-8802fd63-5954-4ce8-b147-2072bd929242.png',
  },
  {
    title: 'Goals',
    description: 'Urbit task manager.',
    color: '#EEDFC9',
    link: '/apps/gol-cli',
    section: SECTIONS.USEFUL,
    desk: 'gol-cli',
    source: '~dister-dozzod-niblyx-malnus',
  },
  {
    title: '%blog',
    description: 'a tool for publishing',
    color: '#573C7C',
    link: '/apps/blog',
    section: SECTIONS.USEFUL,
    desk: 'blog',
    source: '~hanrut-sillet-dachus-tiprel',
  },
  {
    title: 'Board',
    description: 'A tapestry of boards',
    color: '#9E34EB',
    link: '/apps/board',
    section: SECTIONS.FUN,
    desk: 'board',
    source: '~dister-hanfel-dovned',
  },
  {
    title: 'DukeBox',
    description: 'Emulated DOS games on Urbit',
    color: '#209AFA',
    link: '/apps/dukebox',
    section: SECTIONS.FUN,
    desk: 'dukebox',
    source: '~tagrev-lacmur-lomped-firser',
    image:
      'https://cdn.pixabay.com/photo/2012/04/13/11/41/joystick-32023_960_720.png',
  },
  {
    title: 'radio',
    description: 'an app for urbit disc jockeys',
    color: '#FF0000',
    link: '/apps/radio',
    section: SECTIONS.FUN,
    desk: 'radio',
    source: '~nodmyn-dosrux',
    image: 'https://0x0.st/o4--.png',
  },
];
